package br.com.mattje.demo.authorization.studies;

import java.util.*;

public class MatchingStrings {

    public static List<Integer> matchingStrings(List<String> stringList, List<String> queries) {
        // Big O (n*m);
        Map<String, Integer> occurs = new LinkedHashMap<>();
        stringList.forEach(item -> {
            Integer count = occurs.get(item);
            if (count == null) {
                occurs.put(item, 1);
            } else {
                occurs.put(item, ++count);
            }
        });

        List<Integer> matchs = new ArrayList<>();

        for (String item:queries) {
            matchs.add(Objects.requireNonNullElse(occurs.get(item), 0));
        }

        return matchs;

    }

    public static void main(String[] args) {

        List<Integer> finds = matchingStrings(
List.of("lekgdisnsbfdzpqlkg",
"eagemhdygyv",
"jwvwwnrhuai",
"urcadmrwlqe",
"mpgqsvxrijpombyv",
"mpgqsvxrijpombyv",
"urcadmrwlqe",
"mpgqsvxrijpombyv",
"eagemhdygyv",
"eagemhdygyv",
"jwvwwnrhuai",
"urcadmrwlqe",
"jwvwwnrhuai",
"kvugevicpsdf",
"kvugevicpsdf",
"mpgqsvxrijpombyv",
"urcadmrwlqe",
"mpgqsvxrijpombyv",
"exdafbnobg",
"qhootohpnfvbl",
"suffrbmqgnln",
"exdafbnobg",
"exdafbnobg",
"eagemhdygyv",
"mpgqsvxrijpombyv",
"urcadmrwlqe",
"jwvwwnrhuai",
"lekgdisnsbfdzpqlkg",
"mpgqsvxrijpombyv",
"lekgdisnsbfdzpqlkg",
"jwvwwnrhuai",
"exdafbnobg",
"mpgqsvxrijpombyv",
"kvugevicpsdf",
"qhootohpnfvbl",
"urcadmrwlqe",
"kvugevicpsdf",
"mpgqsvxrijpombyv",
"lekgdisnsbfdzpqlkg",
"mpgqsvxrijpombyv",
"kvugevicpsdf",
"qhootohpnfvbl",
"lxyqetmgdbmh",
"urcadmrwlqe",
"urcadmrwlqe",
"kvugevicpsdf",
"lxyqetmgdbmh",
"urcadmrwlqe",
"lxyqetmgdbmh",
"jwvwwnrhuai",
"qhootohpnfvbl",
"qhootohpnfvbl",
"jwvwwnrhuai",
"lekgdisnsbfdzpqlkg",
"kvugevicpsdf",
"mpgqsvxrijpombyv",
"exdafbnobg",
"kvugevicpsdf",
"lekgdisnsbfdzpqlkg",
"qhootohpnfvbl",
"exdafbnobg",
"qhootohpnfvbl",
"exdafbnobg",
"mpgqsvxrijpombyv",
"suffrbmqgnln",
"mpgqsvxrijpombyv",
"qhootohpnfvbl",
"jwvwwnrhuai",
"mpgqsvxrijpombyv",
"qhootohpnfvbl",
"lekgdisnsbfdzpqlkg",
"eagemhdygyv",
"jwvwwnrhuai",
"kvugevicpsdf",
"eagemhdygyv",
"eagemhdygyv",
"lxyqetmgdbmh",
"qhootohpnfvbl",
"lxyqetmgdbmh",
"exdafbnobg",
"qhootohpnfvbl",
"qhootohpnfvbl",
"exdafbnobg",
"suffrbmqgnln",
"mpgqsvxrijpombyv",
"urcadmrwlqe",
"eagemhdygyv",
"lxyqetmgdbmh",
"urcadmrwlqe",
"suffrbmqgnln",
"qhootohpnfvbl",
"kvugevicpsdf",
"lekgdisnsbfdzpqlkg",
"lxyqetmgdbmh",
"mpgqsvxrijpombyv",
"jwvwwnrhuai",
"lxyqetmgdbmh",
"lxyqetmgdbmh",
"lekgdisnsbfdzpqlkg",
"qhootohpnfvbl"),
List.of("exdafbnobg",
"eagemhdygyv",
"mpgqsvxrijpombyv",
"kvugevicpsdf",
"lekgdisnsbfdzpqlkg",
"kvugevicpsdf",
"exdafbnobg",
"qhootohpnfvbl",
"eagemhdygyv",
"kvugevicpsdf",
"suffrbmqgnln",
"jwvwwnrhuai",
"lekgdisnsbfdzpqlkg",
"lekgdisnsbfdzpqlkg",
"mpgqsvxrijpombyv",
"jwvwwnrhuai",
"kvugevicpsdf",
"lekgdisnsbfdzpqlkg",
"exdafbnobg",
"suffrbmqgnln",
"qhootohpnfvbl",
"eagemhdygyv",
"exdafbnobg",
"suffrbmqgnln",
"jwvwwnrhuai",
"qhootohpnfvbl",
"eagemhdygyv",
"exdafbnobg",
"exdafbnobg",
"jwvwwnrhuai",
"qhootohpnfvbl",
"lxyqetmgdbmh",
"qhootohpnfvbl",
"suffrbmqgnln",
"lxyqetmgdbmh",
"qhootohpnfvbl",
"eagemhdygyv",
"jwvwwnrhuai",
"eagemhdygyv",
"qhootohpnfvbl",
"mpgqsvxrijpombyv",
"qhootohpnfvbl",
"jwvwwnrhuai",
"exdafbnobg",
"eagemhdygyv",
"eagemhdygyv",
"kvugevicpsdf",
"kvugevicpsdf",
"jwvwwnrhuai",
"urcadmrwlqe",
"lxyqetmgdbmh",
"qhootohpnfvbl",
"exdafbnobg",
"exdafbnobg",
"eagemhdygyv",
"qhootohpnfvbl",
"exdafbnobg",
"exdafbnobg",
"lekgdisnsbfdzpqlkg",
"jwvwwnrhuai",
"eagemhdygyv",
"urcadmrwlqe",
"kvugevicpsdf",
"lekgdisnsbfdzpqlkg",
"jwvwwnrhuai",
"eagemhdygyv",
"lekgdisnsbfdzpqlkg",
"exdafbnobg",
"kvugevicpsdf",
"jwvwwnrhuai",
"exdafbnobg",
"lxyqetmgdbmh",
"exdafbnobg",
"lxyqetmgdbmh",
"jwvwwnrhuai",
"mpgqsvxrijpombyv",
"eagemhdygyv",
"urcadmrwlqe",
"kvugevicpsdf",
"qhootohpnfvbl",
"jwvwwnrhuai",
"eagemhdygyv",
"urcadmrwlqe",
"urcadmrwlqe",
"exdafbnobg",
"qhootohpnfvbl",
"exdafbnobg",
"eagemhdygyv",
"exdafbnobg",
"jwvwwnrhuai",
"eagemhdygyv",
"jwvwwnrhuai",
"mpgqsvxrijpombyv",
"urcadmrwlqe",
"urcadmrwlqe",
"eagemhdygyv",
"eagemhdygyv",
"jwvwwnrhuai",
"suffrbmqgnln",
"eagemhdygyv")
        );

        finds.forEach(System.out::println);
    }

}
